// apps/cli/src/tui/components/repo-mention-palette.tsx
import { useEffect, useMemo, useState } from 'react';
import type { TextareaRenderable } from '@opentui/core';
import { useKeyboard } from '@opentui/react';

import { useConfigContext } from '../context/config-context.tsx';
import { colors } from '../theme.ts';
import type { InputState } from '../types.ts';

interface RepoMentionPaletteProps {
	inputState: InputState;
	setInputState: (next: InputState | ((prev: InputState) => InputState)) => void;
	inputRef: TextareaRenderable | null;
	cursorPosition: number;
}

export const RepoMentionPalette = (props: RepoMentionPaletteProps) => {
	const config = useConfigContext();

	const [selectedIndex, setSelectedIndex] = useState(0);
	const maxVisible = 8;

	const getDisplayLength = (item: InputState[number]) =>
		item.type === 'pasted' ? `[~${item.lines} lines]`.length : item.content.length;

	const curInputIdx = () => {
		const currentInputIndex = props.cursorPosition;
		let curIdx = 0;
		let totalLength = 0;
		while (curIdx < props.inputState.length) {
			const curItem = props.inputState[curIdx]!;
			const maxIdx = totalLength + getDisplayLength(curItem);
			if (currentInputIndex >= totalLength && currentInputIndex <= maxIdx) {
				break;
			}
			totalLength = maxIdx;
			curIdx++;
		}
		return curIdx;
	};

	const filteredRepos = useMemo(() => {
		const repos = config.repos;
		const curInput = props.inputState[curInputIdx()]?.content;
		if (!curInput) return repos;
		const trimmedInput = curInput.toLowerCase().trim().slice(1);
		return repos.filter((repo) => repo.name.toLowerCase().includes(trimmedInput));
	}, [config.repos, props.inputState, props.cursorPosition]);

	useEffect(() => {
		setSelectedIndex((prev) => {
			if (filteredRepos.length === 0) return 0;
			if (prev >= filteredRepos.length) return filteredRepos.length - 1;
			return prev < 0 ? 0 : prev;
		});
	}, [filteredRepos.length]);

	const visibleRange = useMemo(() => {
		const start = Math.max(
			0,
			Math.min(selectedIndex - Math.floor(maxVisible / 2), filteredRepos.length - maxVisible)
		);
		return {
			start,
			repos: filteredRepos.slice(start, start + maxVisible)
		};
	}, [selectedIndex, filteredRepos]);

	const selectRepo = () => {
		const selectedRepo = filteredRepos[selectedIndex];
		if (!selectedRepo) return;

		const idx = curInputIdx();
		const currentState = props.inputState;
		const newContent = '@' + selectedRepo.name + ' ';
		const next: InputState = [
			...currentState.slice(0, idx),
			{ content: newContent, type: 'mention' as const },
			...currentState.slice(idx + 1)
		];
		props.setInputState(next);

		const inputRef = props.inputRef;
		if (!inputRef) return;

		let newCursorPos = 0;
		for (let i = 0; i <= idx; i++) {
			newCursorPos += i === idx ? newContent.length : getDisplayLength(currentState[i]!);
		}

		const newText = next
			.map((p) => (p.type === 'pasted' ? `[~${p.lines} lines]` : p.content))
			.join('');
		inputRef.setText(newText);
		inputRef.cursorOffset = newCursorPos;
	};

	useKeyboard((key) => {
		if (filteredRepos.length === 0) return;
		switch (key.name) {
			case 'up':
				setSelectedIndex((prev) => (prev > 0 ? prev - 1 : filteredRepos.length - 1));
				break;
			case 'down':
				setSelectedIndex((prev) => (prev < filteredRepos.length - 1 ? prev + 1 : 0));
				break;
			case 'tab':
				selectRepo();
				break;
			case 'return':
				selectRepo();
				break;
			default:
				break;
		}
	});

	if (filteredRepos.length === 0) return null;

	return (
		<box
			style={{
				position: 'absolute',
				bottom: 5,
				left: 1,
				width: 40,
				backgroundColor: colors.bgSubtle,
				border: true,
				borderColor: colors.accent,
				flexDirection: 'column',
				padding: 1
			}}
		>
			<text fg={colors.textMuted} content=" Select resource:" />
			{visibleRange.repos.map((repo, i) => {
				const actualIndex = visibleRange.start + i;
				const isSelected = actualIndex === selectedIndex;
				return (
					<text
						key={repo.name}
						fg={isSelected ? colors.accent : colors.text}
						content={isSelected ? `▸ @${repo.name}` : `  @${repo.name}`}
					/>
				);
			})}
		</box>
	);
};

// apps/cli/src/tui-solid/components/repo-mention-palette.tsx
import { createSignal, createMemo, For, type Component } from 'solid-js';
import { colors } from '../theme.ts';
import { useKeyboard } from '@opentui/solid';
import { useAppContext } from '../context/app-context.tsx';

export const RepoMentionPalette: Component = () => {
	const appState = useAppContext();

	const [selectedIndex, setSelectedIndex] = createSignal(0);

	const maxVisible = 8;

	const curInputIdx = () => {
		const inputRef = appState.inputRef();
		if (!inputRef) return 0;
		const currentInputIndex = inputRef.cursorPosition;
		let curIdx = 0;
		let totalLength = 0;
		const curInputState = appState.inputState();
		while (curIdx < curInputState.length) {
			const curItem = curInputState[curIdx]!;
			const maxIdx = totalLength + curItem.content.length;
			if (currentInputIndex >= totalLength && currentInputIndex <= maxIdx) {
				break;
			}
			totalLength = maxIdx;
			curIdx++;
		}
		return curIdx;
	};

	const filteredRepos = createMemo(() => {
		const repos = appState.repos();
		const curInput = appState.inputState()[curInputIdx()]?.content;
		if (!curInput) return repos;
		const trimmedInput = curInput.toLowerCase().trim().slice(1);
		return repos.filter((repo) => repo.name.toLowerCase().includes(trimmedInput));
	});

	const visibleRange = createMemo(() => {
		const start = Math.max(
			0,
			Math.min(selectedIndex() - Math.floor(maxVisible / 2), filteredRepos().length - maxVisible)
		);
		return {
			start,
			repos: filteredRepos().slice(start, start + maxVisible)
		};
	});

	const selectRepo = () => {
		const selectedRepo = filteredRepos()[selectedIndex()];
		if (selectedRepo) {
			const idx = curInputIdx();
			const currentState = appState.inputState();
			const newContent = '@' + selectedRepo.name + ' ';
			const newState = [
				...currentState.slice(0, idx),
				{ content: newContent, type: 'mention' as const },
				...currentState.slice(idx + 1)
			];
			appState.setInputState(newState);
			const inputRef = appState.inputRef();
			if (inputRef) {
				let newCursorPos = 0;
				for (let i = 0; i <= idx; i++) {
					newCursorPos += i === idx ? newContent.length : currentState[i]!.content.length;
				}
				inputRef.cursorPosition = newCursorPos;
			}
		}
	};

	useKeyboard((key) => {
		switch (key.name) {
			case 'up':
				if (selectedIndex() > 0) {
					setSelectedIndex(selectedIndex() - 1);
				} else {
					setSelectedIndex(filteredRepos().length - 1);
				}
				break;
			case 'down':
				if (selectedIndex() < filteredRepos().length - 1) {
					setSelectedIndex(selectedIndex() + 1);
				} else {
					setSelectedIndex(0);
				}
				break;
			case 'tab':
				selectRepo();
				break;
			case 'return':
				selectRepo();
				break;
			default:
				break;
		}
	});

	return (
		<box
			style={{
				position: 'absolute',
				bottom: 5,
				left: 1,
				width: 40,
				backgroundColor: colors.bgSubtle,
				border: true,
				borderColor: colors.accent,
				flexDirection: 'column',
				padding: 1
			}}
		>
			<text fg={colors.textMuted} content=" Select repo:" />
			<For each={visibleRange().repos}>
				{(repo, i) => {
					const actualIndex = () => visibleRange().start + i();
					const isSelected = () => actualIndex() === selectedIndex();
					return (
						<text
							fg={isSelected() ? colors.accent : colors.text}
							content={isSelected() ? `▸ @${repo.name}` : `  @${repo.name}`}
						/>
					);
				}}
			</For>
		</box>
	);
};
